version: '3.8'

services:
  postgis:
    image: postgis/postgis:latest
    container_name: fire_detection_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: fire_user
      POSTGRES_PASSWORD: fire_pass
      POSTGRES_DB: fire_db
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
