name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Freeze dependencies
        run: pip freeze > requirements.txt

      - name: Run Black (code formatter)
        run: black . > logs/black.log 2>&1

      - name: Run Ruff (linter + fixer)
        run: ruff check . --fix > logs/ruff.log 2>&1

      # - name: Run MyPy (type checker)
      #   run: mypy . --exclude "because_postgres_is_not_playing_along|data|logs|other" > logs/mypy.log 2>&1
      # OR   run: cat logs/mypy.log

      - name: Run Tests with Coverage
        env:
          PYTHONPATH: .
        run: pytest --cov=api --cov=fcts --cov=models --cov-report=html:logs/coverage_html > logs/pytest.log 2>&1
